---
title: "Tidying Data in R"
author: "Priyanka Surio"
date: "August 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in Libraries 

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(dplyr)
library(tidyr)
```

Read in data from [Mike Byerly. 2016. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal](https://knb.ecoinformatics.org/#view/df35b.304.2)

```{r, warning=FALSE, message=FALSE, echo=FALSE}
catch_url <- url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl")
                  
catch_df <- read.csv(catch_url, 
                     stringsAsFactors = FALSE)
head(catch_df)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
catch_df <- catch_df %>% 
  select(-All, -notesRegCode)
#select positively by name(include names of columns you want included without negative sign)
  head(catch_df) #you can put hashes at the end of your code for comments
```

Move from wide to long format using gather and rename catch column to reflect units 


```{r, warning=FALSE, message=FALSE, echo=FALSE}
catch_df <- catch_df %>% 
  gather(key = "species", value = "catch", -Region, -Year) %>% 
  rename(catchThousands = catch)

head(catch_df)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
catch_integers <- as.integer(catch_df$catchThousands)

i <- which(is.na(catch_integers) == T)

catch_df$catchThousands[i]
```
1) turn I into 1 in the catch_thousands column
2) coerce catch_thousands into integer type
3) convert catch_thousands to catch 

```{r, warning=FALSE, message=FALSE, echo=FALSE}
catch_df <- catch_df %>% 
  mutate(catchThousands = ifelse(catchThousands == "I", 1, catchThousands)) %>% 
  mutate (catchThousands = as.integer(catchThousands)) %>% 
  mutate(catch = catchThousands*1000)

tail(catch_df)
```
 
